// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7YUZS14hdyo9IH2vJHGEdYEUPK-u3UzA',
    appId: '1:455239736792:web:c7b8ce8e7a1bad899b66ad',
    messagingSenderId: '455239736792',
    projectId: 'sehatalert-74483',
    authDomain: 'sehatalert-74483.firebaseapp.com',
    storageBucket: 'sehatalert-74483.firebasestorage.app',
    measurementId: 'G-JEHN9NQBL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmj1ZoxCY_gteRHQMEF1V2UDq9Z5tNPMo',
    appId: '1:455239736792:android:3750731a275b5d8b9b66ad',
    messagingSenderId: '455239736792',
    projectId: 'sehatalert-74483',
    storageBucket: 'sehatalert-74483.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaWG33JSHyvOFij83VkwKtSH8I7C1QCVU',
    appId: '1:455239736792:ios:48bd84e7a29c142d9b66ad',
    messagingSenderId: '455239736792',
    projectId: 'sehatalert-74483',
    storageBucket: 'sehatalert-74483.firebasestorage.app',
    iosBundleId: 'com.example.sehatalert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaWG33JSHyvOFij83VkwKtSH8I7C1QCVU',
    appId: '1:455239736792:ios:48bd84e7a29c142d9b66ad',
    messagingSenderId: '455239736792',
    projectId: 'sehatalert-74483',
    storageBucket: 'sehatalert-74483.firebasestorage.app',
    iosBundleId: 'com.example.sehatalert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7YUZS14hdyo9IH2vJHGEdYEUPK-u3UzA',
    appId: '1:455239736792:web:67d29d9ddc75de6e9b66ad',
    messagingSenderId: '455239736792',
    projectId: 'sehatalert-74483',
    authDomain: 'sehatalert-74483.firebaseapp.com',
    storageBucket: 'sehatalert-74483.firebasestorage.app',
    measurementId: 'G-5TQZDCBFT0',
  );
}
